name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true


env:
  JAVA_VERSION: '11'
  JAVA_DISTRO: 'zulu'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Update version
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Updating POMs to version $VERSION"
          ./mvnw -B versions:set -DnewVersion=$VERSION -f pom.xml
          ./mvnw -B versions:set -DnewVersion=$VERSION -f oci-maven-plugin/pom.xml
          ./mvnw -B versions:set -DnewVersion=$VERSION -f oci-maven-plugin-guide/pom.xml
          ./mvnw -B versions:commit
          echo $VERSION > VERSION
          sed -i -e "s/^\:project-version\:\ .*/:project-version: ${VERSION}/g" README.adoc
          git config --global user.email "kordamp-release-bot@kordamp.org"
          git config --global user.name "kordamp-release-bot"
          git commit -a -m "Releasing version $VERSION"
          git push origin master

      - name: Release
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          export GPG_TTY=$(tty)
          ./mvnw -ntp -B --file oci-maven-plugin/pom.xml \
            -Drepository.url=https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git \
            -Dmaven.site.skip=true -Drelease=true deploy

      - name: Build guide
        run: |
          export GPG_TTY=$(tty)
          ./mvnw -ntp -B --file oci-maven-plugin-guide/pom.xml generate-resources

      - name: Publish guide
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: oci-maven-plugin-guide/target/generated-docs

      - name: Release
        uses: jreleaser/release-action@v1
        env:
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          JRELEASER_SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
          JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties